### ISSUE TITLE
Add Windows binary for etaoin pod

### ISSUE THREAD

**Issue by aengelberg** [babashka/pod-babashka-etaoin#7]
I went to build a webdriver-based babashka app on my Windows machine but noticed that this pod only ships for macOS and Linux. Would be great to have a Windows binary if it isn't too much trouble to add to the build script.

**Comment by borkdude** [comment]
I'm open to contributions. Several other pods have an `appveyor.yml` file that builds the project on AppVeyor. I'll add it to my queue of things to do, but feel free to poke at it if you have the time as well, I wouldn't mind if you beat me to it.

**Comment by borkdude** [comment]
@bobisageek Perhaps you're interested in looking at this? I can add an appveyor.yml to this repo to get started with.

**Comment by borkdude** [comment]
OK, the initial build is running here now: https://ci.appveyor.com/project/borkdude/pod-babashka-etaoin
It's failing but the only thing that should happen is to fix the script.bat. There are several approaches possible:

- switch the way of building the uberjar to use clojure -X:uberjar instead of lein for both unix/mac and Windows, like the pod where I copied the appveyor from (which is [this](https://github.com/babashka/pod-babashka-aws) one)
- Convert the script.bar to lein uberjar
- Build using bb scripts so we have one cross platform script (and then use clojure -X:uberjar). 

I have a preference for the latter and I might already be doing this somewhere for other pods or CLIs I've written. One such example is https://github.com/borkdude/jayfu.

**Comment by borkdude** [comment]
@bobisageek has made the Windows build work, thanks!

@aengelberg This is the produced binary on Appveyor: https://ci.appveyor.com/api/buildjobs/jp03y5jqiw0abtbe/artifacts/pod-babashka-etaoin-0.0.2-windows-amd64.zip

Perhaps you can test it locally with `(pods/load-pod "C:\\temp\\pod-babashka-etaoin.exe")` first?

**Comment by borkdude** [comment]
Alright, released the Windows pod as 0.0.3, should work via registry as well.

**Comment by borkdude** [comment]
Thanks a lot @bobisageek !

**Comment by aengelberg** [comment]
Works perfectly for me!

Thanks so much everyone for jumping on this so quickly 🙌
